import test from 'node:test';
import assert from 'node:assert/strict';
import {catalog as source} from '../web/src/catalog.js';
import {blankState,copy,recommend,startSession,expose,submit,result,summarize,makeBackup,parseBackup,mergeStates,validateState,digest,questionPayload,legacyPreview,DAY} from '../web/src/engine.js';
const catalog=copy(source);for(const q of catalog.questions){if(q.asset)q.assetHash='1'.repeat(64);q.hash=await digest(questionPayload(q));}
let seq=0;
function session(st,qs=catalog.questions.slice(0,4),at=1000000000000){st.active=startSession(st,catalog,{selected:qs.map(q=>({q,reason:'synthetic fixture'}))},'test-'+(++seq),at);qs.forEach((q,n)=>expose(st,st.active,n,at));return st.active;}
function answer(s,ok=true,c='sure'){for(const i of s.items)s.answers[i.question.id]={option:ok?i.question.correct:'unknown',confidence:c,note:'synthetic',aided:false,invalid:false,activeMs:1000};}
test('finite 32 original items and eight code contracts',()=>{assert.equal(catalog.questions.length,32);assert.equal(catalog.questions.filter(q=>q.code).length,8);});
test('stable option IDs survive display reordering',()=>{const s=session(blankState());answer(s);s.items.forEach(i=>i.order.reverse());assert.equal(result(s).right,4);});
test('unknown/unanswered wrong, invalid excluded',()=>{const s=session(blankState());answer(s);s.answers[s.items[0].question.id].option='unknown';s.answers[s.items[1].question.id].option=null;s.answers[s.items[2].question.id].invalid=true;const r=result(s);assert.equal(r.right,1);assert.equal(r.total,3);assert.equal(r.invalid,1);assert.equal(r.eligible,false);});
test('all invalid yields no invented score',()=>{const s=session(blankState());Object.values(s.answers).forEach(a=>a.invalid=true);assert.equal(result(s).score,null);});
test('idempotent submission and immutable history copy',()=>{const st=blankState(),s=session(st);answer(s);submit(st);assert.equal(submit(st),null);s.answers[s.items[0].question.id].note='changed';assert.equal(st.sessions.length,1);assert.equal(st.sessions[0].answers[s.items[0].question.id].note,'synthetic');});
test('revealed questions remain exposed even if unanswered',()=>{const st=blankState();session(st);submit(st);const p=recommend(st,catalog,{count:32});const s=startSession(st,catalog,p,'new');assert.equal(s.items.filter(i=>!i.firstSeen).length,4);});
test('aided successes do not become closed-book evidence',()=>{const st=blankState(),s=session(st);answer(s);Object.values(s.answers).forEach(a=>a.aided=true);submit(st);assert.equal(summarize(st,catalog).prob.rows,0);});
test('unvisited questions not diagnosed as conceptual weakness',()=>{const st=blankState();st.active=startSession(st,catalog,{selected:[{q:catalog.questions[0],reason:'fixture'}]},'unvisited');submit(st);assert.equal(summarize(st,catalog).prob.rows,0);});
test('high-confidence error requests new relevant practice',()=>{const st=blankState(),s=session(st,[catalog.questions[0]]);answer(s,false);submit(st);const p=recommend(st,catalog,{count:8});assert(p.summary.prob.misconception);assert(p.selected.some(x=>x.q.skill==='prob'&&!st.exposures[x.q.id]));});
test('mixed eight-question session covers eight starter units',()=>{const p=recommend(blankState(),catalog,{count:8,mode:'mixed'});assert.equal(new Set(p.selected.map(x=>x.q.skill)).size,8);});
test('code mode reports shortage rather than duplicating',()=>{const p=recommend(blankState(),catalog,{count:16,mode:'code'});assert.equal(p.selected.length,8);assert.equal(p.shortfall,8);assert(p.selected.every(x=>x.q.task==='讀碼'));});
test('one-day success is not delayed mastery',()=>{const st=blankState(),s=session(st);answer(s);submit(st);assert.notEqual(summarize(st,catalog).prob.status,'延後複測已確認');});
test('delayed evidence requires families dates and task types',()=>{const st=blankState(),qs=catalog.questions.filter(q=>q.skill==='prob'),t=1000000000000;st.lessons.prob=t-1000;for(let i=0;i<3;i++){const s=session(st,[qs[i]],t+i*DAY);answer(s);submit(st,t+i*DAY);}assert.equal(summarize(st,catalog,t+3*DAY).prob.status,'延後複測已確認');});
test('changed question hashes do not become current evidence',()=>{const st=blankState(),s=session(st);answer(s);submit(st);const next=copy(catalog);next.questions.filter(q=>q.skill==='prob').forEach(q=>q.hash='2'.repeat(64));assert.equal(summarize(st,next).prob.rows,0);});
test('unfinished backup roundtrip',async()=>{const st=blankState();answer(session(st));assert.deepEqual(await parseBackup(await makeBackup(st)),st);});
test('checksum and future schema reject without mutation',async()=>{const st=blankState(),env=JSON.parse(await makeBackup(st));env.data.settings.minutes=120;await assert.rejects(parseBackup(JSON.stringify(env)),/校驗/);const future=copy(st);future.schema=99;assert.throws(()=>validateState(future),/版本/);assert.equal(st.settings.minutes,30);});
test('merge deduplicates identical records, rejects conflicting IDs',()=>{const st=blankState();answer(session(st));submit(st);assert.equal(mergeStates(st,copy(st)).sessions.length,1);const other=copy(st);Object.values(other.sessions[0].answers)[0].note='different';assert.throws(()=>mergeStates(st,other),/不同版本/);assert.equal(st.sessions.length,1);});
test('prototype keys, malformed option order and large notes reject',()=>{const st=blankState();session(st);const bad=copy(st);bad.exposures=JSON.parse('{"__proto__":{"at":1,"family":"prob","revealedAt":null}}');assert.throws(()=>validateState(bad));const order=copy(st);order.active.items[0].order=['o1','o1','o2','o3'];assert.throws(()=>validateState(order));const note=copy(st);Object.values(note.active.answers)[0].note='a'.repeat(4001);assert.throws(()=>validateState(note));});
test('legacy reports are references rather than invented native scores',()=>{assert.equal(legacyPreview('iPAS 原創診斷結果\n總分：50\nQ1｜測試｜作答A').rows,1);assert.throws(()=>legacyPreview('unrecognized'));});
