import {catalog} from './data.js';
import {blankState,copy,recommend,startSession,expose,submit,result,summarize,makeBackup,parseBackup,mergeStates,validateState,legacyPreview,digest,verifyQuestion} from './engine.js';
import {openStorage} from './storage.js';
import {loadFigure} from './assets.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(t,a,d='',c='')=>`<button type="button" data-action="${a}" class="${c}" ${d}>${t}</button>`;
const conf={sure:'有把握',unsure:'不確定',guess:'猜測',unknown:'不會','':'未標記'};
const name=id=>catalog.skills.find(s=>s.id===id)?.name||id;
const date=t=>new Date(t).toLocaleString('zh-TW');
const routes=()=>location.hash.slice(1).split('/');
let state=blankState(),db=null,revision=0,queue=Promise.resolve(),pending=0,saveError='',locked=false,rawRecord=null;
let plan,incoming=null,legacy=null,submitting=false,installEvent=null,priorFocus=null,tick=Date.now(),toastTimer,refreshPending=false;
const assets=new Map();
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
function status(){const n=$('#notice');n.className=saveError?'notice error':'notice';n.innerHTML=saveError?`<b>尚未安全保存</b> ${esc(saveError)} ${btn('匯出目前內容','backup')} ${btn('重新連接','reconnect')}`:pending?'正在保存到這個瀏覽器…':'紀錄僅保存在這個瀏覽器；換機或清理前請匯出備份。';}
function save(){const snapshot=copy(state);pending++;status();queue=queue.then(async()=>{if(locked||!db){saveError||='儲存不可用，目前僅留在記憶體；請匯出備份。';return;}try{revision=await db.write(snapshot,revision);saveError='';}catch(e){locked=true;saveError=e.message;}}).finally(()=>{pending--;status();});return queue;}
function modal(title,html){priorFocus=document.activeElement;$('#modal').innerHTML=`<div class="modal-head"><h2 id="modal-title">${esc(title)}</h2>${btn('關閉','close','','quiet')}</div>${html}`;if(!$('#modal').open)$('#modal').showModal();}
function close(){if($('#modal').open)$('#modal').close();if(priorFocus?.isConnected)priorFocus.focus();}
function download(filename,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function copyBox(text,title='可複製文字'){modal(title,`<p>下載或剪貼簿受限制時，可全選下方文字，再用系統複製。</p><textarea id="copy-text" readonly rows="12">${esc(text)}</textarea><div class="actions">${btn('複製文字','copy-text','','primary')}${btn('全選','select-text')}</div>`);}
function currentQuestion(id){const [page,sid]=routes();return (page==='result'?state.sessions.find(s=>s.id===sid):state.active)?.items.find(i=>i.question.id===id)?.question||catalog.questions.find(q=>q.id===id);}
function refreshAssetUI(q){const[page]=routes();if(page==='practice'&&state.active?.items[state.active.index]?.question.id!==q.id)return;if(!['practice','result'].includes(page))return;if(document.activeElement?.tagName==='TEXTAREA'||$('#modal').open){refreshPending=true;return;}draw();}
function ensureAssets(session){for(const i of session.items){const q=i.question;if(!q.asset||assets.has(q.hash))continue;assets.set(q.hash,{status:'loading'});loadFigure(q).then(url=>{assets.set(q.hash,{status:'ready',url});if(state.active?.id===session.id){state.active.answers[q.id].invalid=false;save();}refreshAssetUI(q);}).catch(e=>{assets.set(q.hash,{status:'error',message:e.message});if(state.active?.id===session.id){state.active.answers[q.id].invalid=true;save();}refreshAssetUI(q);});}}
function figure(q){if(!q.asset)return '';const a=assets.get(q.hash);if(!a||a.status==='loading')return '<div class="asset-state">正在核對必要圖片的版本與完整性…</div>';if(a.status==='error')return `<div class="asset-state error"><b>必要圖片目前不可用</b><p>${esc(a.message)}。本題停止計時並禁止作答；故障題不計錯。已交卷的歷史不因現在的網路狀況改分。</p>${btn('重新載入同版本圖片','retry-image',`data-id="${esc(q.id)}"`)}</div>`;
 const f=q.figure;let table='';if(f?.type==='loss'&&Array.isArray(f.x))table='<tr><th>Epoch</th><th>Training</th><th>Validation</th></tr>'+f.x.map((x,i)=>`<tr><td>${esc(x)}</td><td>${esc(f.train?.[i])}</td><td>${esc(f.validation?.[i])}</td></tr>`).join('');else if(Array.isArray(f?.points))table='<tr><th>順序</th><th>w</th><th>J(w)</th></tr>'+f.points.map(p=>`<tr><td>${esc(p.label)}</td><td>${esc(p.w)}</td><td>${esc((Number(p.w)-2)**2)}</td></tr>`).join('');
 return `<figure><img class="question-image" src="${esc(a.url)}" alt="${esc(f?.title||'原創圖表')}；下方提供等價數值表。"><figcaption>${btn('放大圖片','zoom',`data-id="${esc(q.id)}"`,'quiet')}<span>同站原創資產 · 已校驗</span></figcaption></figure><details><summary>等價数值表（不是提示）</summary><div class="scroll"><table>${table}</table></div></details>`;}
function codeBlock(q){return q.code?`<div class="code-toolbar"><span>Python · 文字程式碼</span>${btn('複製程式','copy-code',`data-id="${esc(q.id)}"`,'quiet')}</div><pre class="code-block" tabindex="0"><code>${esc(q.code)}</code></pre><p class="fine">參照環境：${esc(q.codeCheck?.environment)}。不是即時執行；解析結果已以同一份程式預先驗證。</p>`:'';}
function home(){plan=recommend(state,catalog,{count:({15:4,30:8,60:12,120:16})[state.settings.minutes],mode:state.settings.mode,skill:state.settings.skill,seed:state.sessions.length+1});const unseen=catalog.questions.filter(q=>!state.exposures[q.id]).length;
 return `<div class="eyebrow">每日前進一小步 / FIRST EDITION 0.1</div><section class="hero"><div><span class="pill">手機、平板、電腦都能練</span><h1>不是多背一題，<br>而是真的看懂。</h1><p>用原創變體檢查理解，再依作答證據調整下一小組。</p><div class="hero-stats"><span><b>${unseen}</b> 題尚未看過</span><span><b>${state.sessions.length}</b> 組已完成</span><span><b>8</b> 個短課單元</span></div></div><div class="step-art" aria-hidden="true"><span>理解</span><span>應用</span><span>確認</span></div></section>
 ${state.active?`<section class="card resume"><div><h2>接著上次的進度</h2><p>第${state.active.index+1}／${state.active.items.length}題，原答案與筆記仍保留。</p></div>${btn('繼續這組練習 →','resume','','primary')}</section>`:''}
 <div class="columns"><section class="card"><h2>安排這次練習</h2><div class="form-grid"><label>可用時間<select id="minutes">${[15,30,60,120].map(v=>`<option value="${v}" ${v===state.settings.minutes?'selected':''}>${v}分鐘</option>`).join('')}</select></label><label>練習方式<select id="mode">${[['adaptive','動態補強'],['mixed','混合練習'],['code','程式專練']].map(([v,t])=>`<option value="${v}" ${v===state.settings.mode?'selected':''}>${t}</option>`).join('')}</select></label></div><label>練習範圍<select id="skill"><option value="all">全部單元</option>${catalog.skills.map(s=>`<option value="${s.id}" ${s.id===state.settings.skill?'selected':''}>${s.name}</option>`).join('')}</select></label><p class="muted">${plan.selected.length}題。時間包含短課與檢討，沒有強制倒數。${plan.shortfall>0?`此範圍不足${plan.shortfall}題，不用重複題湊數。`:''}</p>${btn('開始這組練習 →','start',state.active?'disabled':'','primary wide')}<p class="fine">開始後題目固定；這是小型練習，不是正式模考。</p></section>
 <section class="card"><h2>為什麼推薦這些？</h2>${plan.selected.slice(0,3).map(({q,reason})=>`<div class="recommendation"><span class="dot"></span><div><b>${name(q.skill)}</b><p>${esc(reason)} · ${q.task}${state.exposures[q.id]?' · 已見複習':''}</p></div></div>`).join('')}<div class="soft-box">答對但沒把握，不直接視為掌握。答題慢不扣能力分；自由文字理由保留給你檢討，不冒充AI自動判分。</div></section></div><section class="card"><h2>這是可試用的第一版，不是完整考綱題庫</h2><p>32道原創題、8道程式題、2道圖表題及8個短課。四大主題都有樣題，仍有很多考點尚未納入。</p><p class="fine">免登入、無付費API。沒有Android安裝包或完整離線包；個人成績只在本機，換機前請匯出備份。</p></section>`;}
function learn(){const m=summarize(state,catalog);return `<div class="eyebrow">LEARNING MAP</div><h1>先補需要的，再往前走。</h1><p class="lead">本版單元不代表全章覆蓋；狀態只描述這個小題庫的練習證據。</p><div class="skill-grid">${catalog.skills.map(s=>`<article class="card"><span class="eyebrow">${s.topic} · ${s.chapter}</span><h2>${s.name}</h2><p>${esc(m[s.id].status)}${m[s.id].due?' · 到期複習':''}</p><p class="muted">有效閉卷 ${m[s.id].right}/${m[s.id].rows}<br>有把握的新題族成功證據 ${m[s.id].families}個</p><div class="actions">${btn('閱讀短課','lesson',`data-id="${s.id}"`,'primary')}${btn('練這個單元','scope',`data-id="${s.id}"`)}</div></article>`).join('')}</div><section class="card"><h2>來源與勘誤</h2>${catalog.sources.map(s=>`<details><summary>${esc(s.title)}</summary><p>${esc(s.locator)}</p><p>${esc(s.note)}</p></details>`).join('')}<p class="fine">原創題與工程補充都標註定位。公開原始碼包含答案，適用誠實自測，不是防作弊考試。</p></section>`;}
function lesson(id){const s=catalog.skills.find(s=>s.id===id);if(!s)return '<h1>找不到單元</h1>';if(state.active){let changed=false;for(const i of state.active.items)if(i.question.skill===id&&!state.active.answers[i.question.id].forcedAid){Object.assign(state.active.answers[i.question.id],{aided:true,forcedAid:true});changed=true;}if(changed)save();}
 return `<a href="#learn">← 觀念地圖</a><div class="eyebrow">${s.topic}</div><h1>${s.name}</h1>${state.active?'<p class="notice warning">練習中閱讀短課，相關題目已標記有輔助，不影響原始得分。</p>':''}<section class="card lesson">${s.lesson.map((p,i)=>`<div class="lesson-step"><span>${String(i+1).padStart(2,'0')}</span><p>${esc(p)}</p></div>`).join('')}<p class="source">來源：${esc(s.source)}。說明為本站整理與原創補充，非逐字引文。</p>${state.active?btn('返回練習','resume','','primary'):btn('練這個單元','scope',`data-id="${s.id}"`,'primary')}</section>`;}
function practice(){const s=state.active;if(!s)return '<section class="card"><h1>目前沒有未完成的練習</h1><a href="#home">回到首頁</a></section>';ensureAssets(s);const i=s.items[s.index],q=i.question,a=s.answers[q.id],ready=!q.asset||assets.get(q.hash)?.status==='ready',disabled=s.paused||!ready;
 if(!i.shown&&ready&&!s.paused){expose(state,s,s.index);save();}const filled=Object.values(s.answers).filter(a=>a.option!==null).length;
 return `<div class="practice-top"><a href="#home">← 保留進度回首頁</a><span id="timer">${Math.floor(a.activeMs/60000)}:${String(Math.floor(a.activeMs/1000)%60).padStart(2,'0')} 本題有效時間</span>${btn(s.paused?'繼續作答':'暫停','pause','','quiet')}</div><div class="progress-label"><b>第${s.index+1}／${s.items.length}題</b><span>已回應${filled}題（含不會）</span></div><progress value="${filled}" max="${s.items.length}" aria-label="已回應題數"></progress><div class="question-layout"><section class="card"><div class="tags"><span class="pill">${name(q.skill)}</span><span class="pill">${q.task}</span><span class="pill">${i.firstSeen?'未見題':'已見複習'}</span></div><p class="fine">${esc(i.reason)}${!i.familyFresh?' · 同題族已有曝光':''}</p><h1 class="question-title">${esc(q.stem)}</h1>${figure(q)}${codeBlock(q)}${s.paused?'<p class="notice warning">已暫停，計時停止。按「繼續作答」後再選答案。</p>':''}<fieldset class="answers" ${disabled?'disabled':''}><legend class="sr-only">選擇答案</legend>${i.order.map((id,n)=>{const o=q.options.find(o=>o.id===id);return `<label class="answer ${a.option===id?'selected':''}"><input name="answer" type="radio" value="${id}" ${a.option===id?'checked':''}><span class="letter">${'ABCD'[n]}</span><span>${esc(o.text)}</span></label>`;}).join('')}<label class="answer unknown"><input type="radio" name="answer" value="unknown" ${a.option==='unknown'?'checked':''}>我目前不會，先記錄卡點</label></fieldset><fieldset class="confidence" ${disabled?'disabled':''}><legend>這次有多少把握？</legend>${[['sure','有把握'],['unsure','不確定'],['guess','猜測']].map(([v,t])=>`<label><input type="radio" name="confidence" value="${v}" ${a.confidence===v?'checked':''}>${t}</label>`).join('')}</fieldset><label for="note">理由或中間步驟（不自動判分）</label><textarea id="note" rows="3" maxlength="4000" ${disabled?'disabled':''} placeholder="不懂就寫卡在哪一步。">${esc(a.note)}</textarea><label class="check"><input type="checkbox" id="aided" ${a.aided?'checked':''} ${a.forcedAid?'disabled':''}>曾看提示、查資料、問AI或執行程式。${a.forcedAid?'（本站提示已使用，不能取消）':''}</label><div class="actions">${btn('看提示（標記輔助）','hint',`data-id="${esc(q.id)}"`,'quiet')}${btn('回報題目問題','issue',`data-id="${esc(q.id)}"`)}</div></section><aside class="card"><h2>這組的題目</h2><div class="question-nav">${s.items.map((x,n)=>`<button data-action="jump" data-index="${n}" class="${n===s.index?'current':''} ${s.answers[x.question.id].option!==null?'done':''}" aria-label="跳至第${n+1}題">${n+1}</button>`).join('')}</div><p class="source">考點來源：${esc(q.source)}</p><p class="fine">不用硬猜。一次錯誤不會替你下永久結論。</p></aside></div><div class="practice-actions">${btn('← 上一題','move',`data-delta="-1" ${s.index===0?'disabled':''}`)}${btn('下一題 →','move',`data-delta="1" ${s.index===s.items.length-1?'disabled':''}`)}${btn('交卷並看解析','confirm-submit','','primary')}</div>`;}
function history(){const m=summarize(state,catalog);return `<div class="eyebrow">YOUR EVIDENCE, NOT A PREDICTION</div><h1>把進步留下來。</h1><p class="lead">首次未見題、程式與有輔助練習分開看，不用重做後的高分假裝已學會。</p><section class="card"><h2>各單元有效閉卷作答</h2>${catalog.skills.map(s=>`<div class="history-row"><div><b>${s.name}</b><small>${esc(m[s.id].status)}${m[s.id].due?' · 待複習':''}</small></div><strong>${m[s.id].right}/${m[s.id].rows}</strong></div>`).join('')}<p class="fine">有輔助、故障題及與目前題庫指紋不符的舊題，均不計入這張表。</p></section><section class="card"><h2>每次練習都保留</h2>${state.sessions.length?state.sessions.slice().reverse().map(s=>{const r=result(s);return `<a href="#result/${s.id}" class="history-row"><div><b>${date(s.submittedAt)}</b><small>${r.original}題 · 程式${r.codeRight}/${r.codeTotal} · 技術無效${r.invalid}</small></div><strong>${r.right}/${r.total} →</strong></a>`;}).join(''):'<p>尚未交卷。先從一小組開始。</p>'}</section>${state.legacy.length?`<section class="card"><h2>舊報告（只作參照）</h2><p>尚未逐题重新核驗，不計入本站能力證據。</p>${state.legacy.map(r=>`<details><summary>${date(r.at)} 匯入</summary><pre class="report-text">${esc(r.text)}</pre></details>`).join('')}</section>`:''}`;}
function reportText(s){const r=result(s);return [`iPAS 科目三｜學習步調 ${catalog.appVersion}`,`題庫：${s.bankVersion}`,`練習ID：${s.id}`,`交卷：${date(s.submittedAt)}`,`有效題：${r.right}/${r.total}；原題數${r.original}；技術無效${r.invalid}`,`首次未見且未標輔助：${r.freshRight}/${r.freshTotal}`,`程式：${r.codeRight}/${r.codeTotal}`,'用途：原創練習，不是正式分數推估','',...s.items.flatMap((i,n)=>{const q=i.question,a=s.answers[q.id];return [`${n+1}. ${q.id} v${q.version}｜${name(q.skill)}｜${q.task}`,`作答：${a.option==='unknown'?'不會':q.options.find(o=>o.id===a.option)?.text||'未答'}；${conf[a.confidence]}`,`結果：${a.invalid?'技術無效':a.option===q.correct?'答對':'未答對'}；輔助：${a.aided?'有':'未標記'}`,`理由：${a.note||'未填'}`,`正解：${q.options.find(o=>o.id===q.correct).text}`,`解析：${q.explanation}`,`來源：${q.source}`,''];})].join('\n');}
function review(id){const s=state.sessions.find(s=>s.id===id);if(!s)return '<h1>找不到這份紀錄</h1>';ensureAssets(s);const r=result(s);return `<a href="#history">← 全部紀錄</a><div class="eyebrow">SESSION REVIEW</div><h1>看懂錯在哪，比分數更重要。</h1><div class="stat-grid"><section class="card big-stat"><span>有效題答對</span><b>${r.right}<small>/${r.total}</small></b><p>${r.invalid?'有技術無效題，本回不作驗收':`本組${r.score?.toFixed(1)??'—'}分，非正式分數推估`}</p></section><section class="card big-stat"><span>首次未見、未標輔助</span><b>${r.freshRight}<small>/${r.freshTotal}</small></b><p>不與重做成績混合</p></section><section class="card big-stat"><span>程式題</span><b>${r.codeRight}<small>/${r.codeTotal}</small></b><p>拆開確認讀碼能力</p></section></div><section class="card"><p>${date(s.submittedAt)} · 題庫${esc(s.bankVersion)}。下一組依新的有效證據重新安排。</p><div class="actions">${btn('下載學習報告TXT','report-download',`data-session="${s.id}"`,'primary')}${btn('顯示可複製報告','report-copy',`data-session="${s.id}"`)}<a href="#home" class="button">安排下一組 →</a></div></section><h2>逐題解析</h2>${s.items.map((i,n)=>{const q=i.question,a=s.answers[q.id],good=a.option===q.correct;return `<details class="card review"><summary><span class="number">${n+1}</span><div><b>${name(q.skill)} · ${q.task}</b><small>${a.invalid?'技術無效、不計分':good?'答對':'未答對'} · ${conf[a.confidence]}${a.aided?' · 有輔助':''}${good&&a.confidence!=='sure'?' · 換題確認':''}${!good&&a.confidence==='sure'?' · 優先核對觀念':''}</small></div></summary><h3>${esc(q.stem)}</h3>${figure(q)}${codeBlock(q)}<div class="answer-explanation"><b>正解：${esc(q.options.find(o=>o.id===q.correct).text)}</b><p>${esc(q.explanation)}</p></div>${q.options.map(o=>`<div class="option-review"><b>${o.id===q.correct?'✓ ':''}${esc(o.text)}${o.id===a.option?' ← 你的選擇':''}</b><p>${esc(o.why)}</p></div>`).join('')}<div class="soft-box"><b>你留下的理由</b><p>${esc(a.note||'未填寫')}</p></div><p class="source">${esc(q.source)} · ${esc(q.id)} v${q.version}</p>${btn('回報這一題','issue',`data-id="${esc(q.id)}"`)}</details>`;}).join('')}`;}
function settings(){return `<div class="eyebrow">LOCAL FIRST</div><h1>你的紀錄，由你帶走。</h1><p class="lead">免帳號。手機與電腦先用JSON匯出／匯入換機，不會自動同步。</p><div class="columns"><section class="card"><h2>備份與恢復</h2><p>備份含未完成練習與筆記。匯入先校驗並預覽，不靜默覆蓋同ID的不同內容。</p><div class="actions">${btn('匯出完整JSON備份','backup','','primary')}${btn('顯示備份文字','backup-text')}</div><label class="file-input">選擇JSON或舊報告TXT<input type="file" id="import-file" accept=".json,.txt,application/json,text/plain"></label><label for="import-text">或貼上備份／舊報告</label><textarea id="import-text" rows="5" maxlength="5242880"></textarea>${btn('校驗並預覽匯入','preview-import','','primary')}<p class="fine">最大5MB。舊HTML TXT只保存作參照，不冒充重新核驗的得分。不要把個人備份貼到公開GitHub。</p>${rawRecord?btn('匯出原始儲存資料供復原','raw-backup'):''}</section><section class="card"><h2>手機與Android方向</h2><p>手機底部導覽、觸控選項、程式橫向捲動、圖表放大都已設計。相容瀏覽器可從選單加入主畫面。</p>${installEvent?btn('加入主畫面','install','','primary'):''}<div class="soft-box"><b>目前是網站，不是APK。</b> 尚無完整離線包。日後可沿用題庫與純函式規則，另接Android原生儲存、返回鍵與檔案分享。</div><h3>保存狀態</h3><p>${saveError?esc(saveError):'已連接本機IndexedDB，但瀏覽器清理仍可能移除資料。'}</p>${btn('請求較持久的本機儲存','persist','','quiet')}${btn('重新連接／載入較新紀錄','reconnect','','quiet')}</section></div><section class="card"><h2>版本與限制</h2><p>應用程式${catalog.appVersion} · 題庫${catalog.version} · 32題／8程式／2圖表。純本機選題，沒有生成式AI、追蹤分析或付費API。</p><p>沒有無限生成題、自動讀懂自由文字、完整正式模考或通過率預測。小題庫不足時明確顯示不足；已見題不冒充未見驗收。</p><a href="https://github.com/SmailDot/iPASS_AI_exams" target="_blank" rel="noopener">查看GitHub版本紀錄 ↗</a></section>`;}
function draw(){const[p,id]=routes();document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===(p==='lesson'?'learn':p==='result'?'history':p==='practice'?'home':p||'home');if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});try{$('#main').innerHTML=p==='practice'?practice():p==='learn'?learn():p==='lesson'?lesson(id):p==='history'?history():p==='result'?review(id):p==='settings'?settings():home();}catch(e){$('#main').innerHTML=`<section class="card"><h1>畫面暫時無法顯示</h1><p>${esc(e.message)}</p><p>沒有自動刪除資料，請先備份。</p>${btn('匯出目前內容','backup')}</section>`;}status();}
async function importPreview(text){try{if(text.trimStart().startsWith('{')){incoming=await parseBackup(text);legacy=null;const merged=mergeStates(state,incoming);modal('確認合併備份',`<p>備份含${incoming.sessions.length}組完成練習${incoming.active?'及1組未完成練習':''}，合併後${merged.sessions.length}組。保留本機設定，不傳送資料到伺服器。</p><p>不同題目指紋的舊紀錄只作歷史，不納入目前學習證據。</p>${btn('確認合併','apply-import','','primary')}${btn('取消','close')}`);}else{const p=legacyPreview(text);legacy=text;incoming=null;modal('舊報告預覽',`<p>辨識到${p.rows}行逐題紀錄。</p><pre class="report-text">${esc(p.summary.join('\n'))}</pre><p>只保存作參照，不重建未知題目或得分。</p>${btn('保存為參照報告','apply-import','','primary')}`);}}catch(e){incoming=legacy=null;modal('未匯入任何資料',`<p class="error">${esc(e.message)}</p><p>目前紀錄維持原樣。</p>`);}}
async function action(b){const a=b.dataset.action,id=b.dataset.id,s=state.active;if(a==='close'){close();return;}
 if(a==='start'){if(s)return;state.active=startSession(state,catalog,plan,crypto.randomUUID());save();location.hash='practice';return;}
 if(a==='resume'){if(s){s.paused=false;save();}location.hash='practice';draw();return;}
 if(a==='pause'){s.paused=!s.paused;tick=Date.now();save();draw();return;}
 if(a==='move'||a==='jump'){if(!s)return;s.index=a==='jump'?Number(b.dataset.index):Math.max(0,Math.min(s.items.length-1,s.index+Number(b.dataset.delta)));save();draw();$('#main').focus();window.scrollTo(0,0);return;}
 if(a==='confirm-submit'){if(!s)return;if(s.items.some(i=>i.question.asset&&assets.get(i.question.hash)?.status==='loading'))return toast('必要圖片仍在校驗，請稍候。');const answers=Object.values(s.answers),missing=answers.filter(x=>x.option===null&&!x.invalid).length,invalid=answers.filter(x=>x.invalid).length;modal('確認交卷',`<p>交卷後鎖定這次紀錄並顯示解析。重做不覆寫第一次。</p><div class="soft-box">未作答${missing}題 · 未標信心${answers.filter(x=>!x.confidence).length}題 · 素材無效${invalid}題</div><p>${invalid?'無效題不扣分，本回不作驗收證據。':'未作答題列為未答對。'}</p><div class="actions">${btn('確認交卷並看解析','submit','','primary')}${btn('返回檢查','close')}</div>`);return;}
 if(a==='submit'){if(submitting||!s)return;submitting=true;b.disabled=true;const completed=submit(state);await save();close();location.hash='result/'+completed.id;draw();submitting=false;return;}
 if(a==='lesson'){state.lessons[id]=Date.now();save();close();location.hash='lesson/'+id;draw();return;}
 if(a==='scope'){state.settings.skill=id;state.settings.mode='adaptive';save();close();location.hash='home';draw();return;}
 if(a==='hint'){const q=currentQuestion(id);if(!s)return;Object.assign(s.answers[id],{aided:true,forcedAid:true});save();modal('提示：先釐清這一步',`<p>${esc(q.hint)}</p><p class="fine">此題已標記有輔助，不作閉卷證據。</p>${btn('閱讀相關短課','lesson',`data-id="${esc(q.skill)}"`,'primary')}`);return;}
 if(a==='retry-image'){const q=currentQuestion(id);assets.delete(q.hash);loadFigure(q,{retry:true}).catch(()=>{});draw();return;}
 if(a==='zoom'){const q=currentQuestion(id),v=assets.get(q.hash);if(v?.status==='ready')modal('圖表放大',`<div class="zoom-scroll"><img src="${esc(v.url)}" alt="${esc(q.figure?.title)}"></div><p class="fine">小螢幕可在圖框內左右捲動，原題另有等價數值表。</p>`);return;}
 if(a==='copy-code'){copyBox(currentQuestion(id).code,'程式文字（不含行號）');return;}
 if(a==='copy-text'){try{await navigator.clipboard.writeText($('#copy-text').value);toast('已複製');}catch{$('#copy-text').focus();$('#copy-text').select();toast('剪貼簿受限制，已選取文字，請使用系統複製。');}return;}
 if(a==='select-text'){$('#copy-text').focus();$('#copy-text').select();return;}
 if(a==='backup'||a==='backup-text'){const text=await makeBackup(state);if(a==='backup-text')copyBox(text,'JSON備份（含個人紀錄）');else{download('ipas-backup-'+new Date().toISOString().slice(0,10)+'.json',text,'application/json');modal('備份已準備',`<p>請確認下載資料夾已有JSON。下載受限時可改用複製；不要貼到公開儲存庫。</p>${btn('顯示備份文字','backup-text','','primary')}`);}return;}
 if(a==='raw-backup'){download('ipas-original-storage.json',JSON.stringify(rawRecord,null,2),'application/json');return;}
 if(a==='preview-import'){await importPreview($('#import-text').value);return;}
 if(a==='apply-import'){if(incoming)state=mergeStates(state,incoming);else if(legacy){const hash=await digest(legacy);if(!state.legacy.some(r=>r.id===hash))state.legacy.push({id:hash,at:Date.now(),text:legacy});}else return;incoming=legacy=null;await save();close();draw();toast(saveError?'已合併至記憶體，尚未安全保存。':'匯入完成');return;}
 if(a==='report-download'||a==='report-copy'){const r=state.sessions.find(x=>x.id===b.dataset.session);if(a==='report-copy')copyBox(reportText(r),'學習報告');else{download('ipas-learning-report.txt',reportText(r));toast('請確認TXT已下載；也可顯示可複製報告。');}return;}
 if(a==='issue'){const q=currentQuestion(id);copyBox(`題目問題回報\n應用程式：${catalog.appVersion}\n題庫：${catalog.version}\n題目：${q.id} v${q.version}\n問題描述：\n\n請自行補充。未附上你的答案、筆記或備份。`,'問題回報範本（不自動送出）');return;}
 if(a==='persist'){const ok=await navigator.storage?.persist?.();toast(ok?'已獲較持久儲存權限，仍請備份。':'瀏覽器未授權，請保留外部備份。');return;}
 if(a==='reconnect'){await queue;if(!db)db=await openStorage();const record=await db.read();if(record.data){try{validateState(record.data);}catch(e){rawRecord=record;locked=true;throw new Error('原有資料版本不相容或損壞，已保留且禁止覆寫。可到設定匯出原始資料。');}}if(record.revision!==revision||rawRecord){rawRecord=record;modal('載入另一份本機紀錄',`<p>先匯出此頁未保存內容再載入。此操作不會覆寫資料庫。</p>${btn('先匯出此頁','backup')}${btn('載入儲存版本','load-stored','','primary')}`);}else{locked=false;saveError='';await save();toast(saveError||'重新保存成功');}return;}
 if(a==='load-stored'){if(!rawRecord?.data)return;validateState(rawRecord.data);state=copy(rawRecord.data);revision=rawRecord.revision;rawRecord=null;locked=false;saveError='';close();draw();return;}
 if(a==='install'&&installEvent){await installEvent.prompt();installEvent=null;draw();return;}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;action(b).catch(error=>{submitting=false;toast(error.message||'操作未完成，沒有自動清除資料。');});});
document.addEventListener('change',e=>{const t=e.target;if(['minutes','mode','skill'].includes(t.id)){state.settings[t.id]=t.id==='minutes'?Number(t.value):t.value;save();draw();return;}if(t.id==='import-file'){const f=t.files[0];if(!f)return;if(f.size>5*1024*1024)return toast('檔案超過5MB，沒有匯入。');f.text().then(importPreview).catch(e=>toast(e.message));return;}const s=state.active;if(!s)return;const a=s.answers[s.items[s.index].question.id];if(t.name==='answer'){a.option=t.value;if(t.value==='unknown')a.confidence='unknown';save();draw();$(`input[name="answer"][value="${t.value}"]`)?.focus();}if(t.name==='confidence'){a.confidence=t.value;save();}if(t.id==='aided'){a.aided=!!a.forcedAid||t.checked;save();}});
document.addEventListener('input',e=>{if(e.target.id==='note'&&state.active){state.active.answers[state.active.items[state.active.index].question.id].note=e.target.value;save();}});
document.addEventListener('focusout',()=>{if(refreshPending)setTimeout(()=>{if(document.activeElement?.tagName!=='TEXTAREA'&&!$('#modal').open){refreshPending=false;draw();}},0);});
window.addEventListener('hashchange',()=>{close();draw();$('#main').focus();window.scrollTo(0,0);});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;if(routes()[0]==='settings')draw();});
document.addEventListener('visibilitychange',()=>{tick=Date.now();if(state.active)save();});
window.addEventListener('pagehide',()=>{if(state.active)save();});
setInterval(()=>{const now=Date.now(),dt=Math.max(0,Math.min(2000,now-tick));tick=now;const s=state.active;if(!s||s.paused||document.hidden||routes()[0]!=='practice'||$('#modal').open)return;const q=s.items[s.index].question;if(q.asset&&assets.get(q.hash)?.status!=='ready')return;const a=s.answers[q.id];a.activeMs+=dt;if($('#timer'))$('#timer').textContent=`${Math.floor(a.activeMs/60000)}:${String(Math.floor(a.activeMs/1000)%60).padStart(2,'0')} 本題有效時間`;if(Math.floor(a.activeMs/1000)%10===0)save();},1000);
async function boot(){try{if(!(await Promise.all(catalog.questions.map(verifyQuestion))).every(Boolean))throw new Error('題庫指紋不符，請重新載入完整版本。');try{db=await openStorage();const record=await db.read();revision=record.revision;if(record.data){rawRecord=record;validateState(record.data);state=record.data;rawRecord=null;}}catch(e){locked=true;saveError='本機紀錄未成功讀取：'+e.message+'。沒有清空原資料。';}draw();}catch(e){$('#main').innerHTML=`<section class="card"><h1>練習站未成功啟動</h1><p>${esc(e.message)}</p><p>沒有刪除本機紀錄。請核對是否使用HTTPS或localhost，並重新整理。</p></section>`;}}
boot();
